---

- name: Networking | Disable selinux
  become: yes
  selinux:
    state: disabled

- name: Networking | Disable Firewalld
  become: yes
  service:
       name: firewalld
       state: stopped
       enabled: False

- name: Installing Common Packages
  become: yes
  yum:
    name:
      - wget
      - rsync
      - mlocate
      - epel-release
      - ntp
      - awscli
    state: latest

- name: Installing python-pip 
  become: yes
  yum:
    name:  python-pip
    state: latest

- name: Check 2ndquadrant repo
  shell: rpm -q barman-cli
  register: rpm_check
  ignore_errors: yes

- name: Installing Barman-cli on Standby
  become: yes
  shell: curl https://dl.2ndquadrant.com/default/release/get/11/rpm | sudo bash
  when: rpm_check.rc > 0

- name: Installing barman-cli on all host
  become: yes
  yum:
    name:
      - barman-cli-2.10-2.el7
    state: present
  
- name: Check hostname
  shell: /bin/cat /etc/hostname
  register: host_name

- name: Change all hostname 
  block: 
  - name: Fix hostname
    become: yes
    shell: hostname "{{ hostvars[inventory_hostname].hostname}}"

  - name: Fix hostname
    become: yes
    shell: echo "{{ hostvars[inventory_hostname].hostname}}" > /etc/hostname
     
  when: host_name.stdout_lines[0] != hostvars[inventory_hostname].hostname
  
- name: Fix file hosts
  become: yes
  template:
    src: hosts.j2 
    dest: "/etc/hosts" 